# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug64
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/jpeg
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libjpeg.so
  DEFINES   += -D_DEBUG -DENABLE_FREE_TYPE2=1 -DENABLE_FONT_CONFIG=1
  INCLUDES  += -I../third_party/libjpeg-turbo-1.4.1 -I../third_party/libjpeg-turbo-1.4.1/build -I../third_party/libjpeg-turbo-1.4.1/simd
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -msse2 -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/jpeg
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libjpeg.so
  DEFINES   += -DNDEBUG -DENABLE_FREE_TYPE2=1 -DENABLE_FONT_CONFIG=1
  INCLUDES  += -I../third_party/libjpeg-turbo-1.4.1 -I../third_party/libjpeg-turbo-1.4.1/build -I../third_party/libjpeg-turbo-1.4.1/simd
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -Wall -msse2 -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -m64 -L/usr/lib64
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/jpeg
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libjpeg.so
  DEFINES   += -D_DEBUG -DENABLE_FREE_TYPE2=1 -DENABLE_FONT_CONFIG=1
  INCLUDES  += -I../third_party/libjpeg-turbo-1.4.1 -I../third_party/libjpeg-turbo-1.4.1/build -I../third_party/libjpeg-turbo-1.4.1/simd
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -msse2 -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/jpeg
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libjpeg.so
  DEFINES   += -DNDEBUG -DENABLE_FREE_TYPE2=1 -DENABLE_FONT_CONFIG=1
  INCLUDES  += -I../third_party/libjpeg-turbo-1.4.1 -I../third_party/libjpeg-turbo-1.4.1/build -I../third_party/libjpeg-turbo-1.4.1/simd
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -Wall -msse2 -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -m32 -L/usr/lib32
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/jcapimin.o \
	$(OBJDIR)/jcapistd.o \
	$(OBJDIR)/jccoefct.o \
	$(OBJDIR)/jccolor.o \
	$(OBJDIR)/jcdctmgr.o \
	$(OBJDIR)/jchuff.o \
	$(OBJDIR)/jcinit.o \
	$(OBJDIR)/jcmainct.o \
	$(OBJDIR)/jcmarker.o \
	$(OBJDIR)/jcmaster.o \
	$(OBJDIR)/jcomapi.o \
	$(OBJDIR)/jcparam.o \
	$(OBJDIR)/jcphuff.o \
	$(OBJDIR)/jcprepct.o \
	$(OBJDIR)/jcsample.o \
	$(OBJDIR)/jctrans.o \
	$(OBJDIR)/jdapimin.o \
	$(OBJDIR)/jdapistd.o \
	$(OBJDIR)/jdatadst.o \
	$(OBJDIR)/jdatasrc.o \
	$(OBJDIR)/jdcoefct.o \
	$(OBJDIR)/jdcolor.o \
	$(OBJDIR)/jddctmgr.o \
	$(OBJDIR)/jdhuff.o \
	$(OBJDIR)/jdinput.o \
	$(OBJDIR)/jdmainct.o \
	$(OBJDIR)/jdmarker.o \
	$(OBJDIR)/jdmaster.o \
	$(OBJDIR)/jdmerge.o \
	$(OBJDIR)/jdphuff.o \
	$(OBJDIR)/jdpostct.o \
	$(OBJDIR)/jdsample.o \
	$(OBJDIR)/jdtrans.o \
	$(OBJDIR)/jerror.o \
	$(OBJDIR)/jfdctflt.o \
	$(OBJDIR)/jfdctfst.o \
	$(OBJDIR)/jfdctint.o \
	$(OBJDIR)/jidctflt.o \
	$(OBJDIR)/jidctfst.o \
	$(OBJDIR)/jidctint.o \
	$(OBJDIR)/jidctred.o \
	$(OBJDIR)/jquant1.o \
	$(OBJDIR)/jquant2.o \
	$(OBJDIR)/jutils.o \
	$(OBJDIR)/jmemmgr.o \
	$(OBJDIR)/jmemnobs.o \
	$(OBJDIR)/jaricom.o \
	$(OBJDIR)/jcarith.o \
	$(OBJDIR)/jdarith.o \
	$(OBJDIR)/turbojpeg.o \
	$(OBJDIR)/transupp.o \
	$(OBJDIR)/jdatadst-tj.o \
	$(OBJDIR)/jdatasrc-tj.o \
	$(OBJDIR)/jsimd_none.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking jpeg
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning jpeg
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/jcapimin.o: ../third_party/libjpeg-turbo-1.4.1/jcapimin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcapistd.o: ../third_party/libjpeg-turbo-1.4.1/jcapistd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jccoefct.o: ../third_party/libjpeg-turbo-1.4.1/jccoefct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jccolor.o: ../third_party/libjpeg-turbo-1.4.1/jccolor.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcdctmgr.o: ../third_party/libjpeg-turbo-1.4.1/jcdctmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jchuff.o: ../third_party/libjpeg-turbo-1.4.1/jchuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcinit.o: ../third_party/libjpeg-turbo-1.4.1/jcinit.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcmainct.o: ../third_party/libjpeg-turbo-1.4.1/jcmainct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcmarker.o: ../third_party/libjpeg-turbo-1.4.1/jcmarker.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcmaster.o: ../third_party/libjpeg-turbo-1.4.1/jcmaster.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcomapi.o: ../third_party/libjpeg-turbo-1.4.1/jcomapi.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcparam.o: ../third_party/libjpeg-turbo-1.4.1/jcparam.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcphuff.o: ../third_party/libjpeg-turbo-1.4.1/jcphuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcprepct.o: ../third_party/libjpeg-turbo-1.4.1/jcprepct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcsample.o: ../third_party/libjpeg-turbo-1.4.1/jcsample.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jctrans.o: ../third_party/libjpeg-turbo-1.4.1/jctrans.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdapimin.o: ../third_party/libjpeg-turbo-1.4.1/jdapimin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdapistd.o: ../third_party/libjpeg-turbo-1.4.1/jdapistd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdatadst.o: ../third_party/libjpeg-turbo-1.4.1/jdatadst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdatasrc.o: ../third_party/libjpeg-turbo-1.4.1/jdatasrc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdcoefct.o: ../third_party/libjpeg-turbo-1.4.1/jdcoefct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdcolor.o: ../third_party/libjpeg-turbo-1.4.1/jdcolor.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jddctmgr.o: ../third_party/libjpeg-turbo-1.4.1/jddctmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdhuff.o: ../third_party/libjpeg-turbo-1.4.1/jdhuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdinput.o: ../third_party/libjpeg-turbo-1.4.1/jdinput.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdmainct.o: ../third_party/libjpeg-turbo-1.4.1/jdmainct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdmarker.o: ../third_party/libjpeg-turbo-1.4.1/jdmarker.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdmaster.o: ../third_party/libjpeg-turbo-1.4.1/jdmaster.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdmerge.o: ../third_party/libjpeg-turbo-1.4.1/jdmerge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdphuff.o: ../third_party/libjpeg-turbo-1.4.1/jdphuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdpostct.o: ../third_party/libjpeg-turbo-1.4.1/jdpostct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdsample.o: ../third_party/libjpeg-turbo-1.4.1/jdsample.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdtrans.o: ../third_party/libjpeg-turbo-1.4.1/jdtrans.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jerror.o: ../third_party/libjpeg-turbo-1.4.1/jerror.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jfdctflt.o: ../third_party/libjpeg-turbo-1.4.1/jfdctflt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jfdctfst.o: ../third_party/libjpeg-turbo-1.4.1/jfdctfst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jfdctint.o: ../third_party/libjpeg-turbo-1.4.1/jfdctint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jidctflt.o: ../third_party/libjpeg-turbo-1.4.1/jidctflt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jidctfst.o: ../third_party/libjpeg-turbo-1.4.1/jidctfst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jidctint.o: ../third_party/libjpeg-turbo-1.4.1/jidctint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jidctred.o: ../third_party/libjpeg-turbo-1.4.1/jidctred.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jquant1.o: ../third_party/libjpeg-turbo-1.4.1/jquant1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jquant2.o: ../third_party/libjpeg-turbo-1.4.1/jquant2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jutils.o: ../third_party/libjpeg-turbo-1.4.1/jutils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jmemmgr.o: ../third_party/libjpeg-turbo-1.4.1/jmemmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jmemnobs.o: ../third_party/libjpeg-turbo-1.4.1/jmemnobs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jaricom.o: ../third_party/libjpeg-turbo-1.4.1/jaricom.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jcarith.o: ../third_party/libjpeg-turbo-1.4.1/jcarith.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdarith.o: ../third_party/libjpeg-turbo-1.4.1/jdarith.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/turbojpeg.o: ../third_party/libjpeg-turbo-1.4.1/turbojpeg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/transupp.o: ../third_party/libjpeg-turbo-1.4.1/transupp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdatadst-tj.o: ../third_party/libjpeg-turbo-1.4.1/jdatadst-tj.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jdatasrc-tj.o: ../third_party/libjpeg-turbo-1.4.1/jdatasrc-tj.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/jsimd_none.o: ../third_party/libjpeg-turbo-1.4.1/jsimd_none.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
