# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := flowers
DEFS_Debug := \
	'-D_DEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Debug := \
	`pkg-config --cflags gtk+-2.0`

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-O0 \
	-Wall \
	-g \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Debug := \
	-I$(srcdir)/include \
	-I$(srcdir)/build \
	-I$(srcdir)/demos

DEFS_Release := \
	'-DNDEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Release := \
	`pkg-config --cflags gtk+-2.0`

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-O3 \
	-Wall \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Release := \
	-I$(srcdir)/include \
	-I$(srcdir)/build \
	-I$(srcdir)/demos

OBJS := \
	$(obj).target/$(TARGET)/demos/flowers.o \
	$(obj).target/$(TARGET)/demos/platform_gtk2.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(builddir)/lib.target/libpicasso2_sw.so $(obj).target/libpicasso2_sw.so

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-rpath=\$$ORIGIN/lib.target/ \
	-Wl,-rpath-link=\$(builddir)/lib.target/

LDFLAGS_Release := \
	-Wl,-rpath=\$$ORIGIN/lib.target/ \
	-Wl,-rpath-link=\$(builddir)/lib.target/

LIBS := \
	-lfreetype \
	-lz `pkg-config --libs gtk+-2.0`

$(builddir)/flowers: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/flowers: LIBS := $(LIBS)
$(builddir)/flowers: LD_INPUTS := $(OBJS) $(obj).target/libpicasso2_sw.so
$(builddir)/flowers: TOOLSET := $(TOOLSET)
$(builddir)/flowers: $(OBJS) $(obj).target/libpicasso2_sw.so FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/flowers
# Add target alias
.PHONY: flowers
flowers: $(builddir)/flowers

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/flowers

