# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := gif
### Rules for action "install_header1":
quiet_cmd_picasso_gyp_gif_target_install_header1 = ACTION picasso_gyp_gif_target_install_header1 $@
cmd_picasso_gyp_gif_target_install_header1 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/giflib-5.1.3/lib/gif_lib.h "$(builddir)/include/gif_lib.h"

$(builddir)/include/gif_lib.h: obj := $(abs_obj)
$(builddir)/include/gif_lib.h: builddir := $(abs_builddir)
$(builddir)/include/gif_lib.h: TOOLSET := $(TOOLSET)
$(builddir)/include/gif_lib.h: $(srcdir)/third_party/giflib-5.1.3/lib/gif_lib.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_gif_target_install_header1)

all_deps += $(builddir)/include/gif_lib.h
action_picasso_gyp_gif_target_install_header1_outputs := $(builddir)/include/gif_lib.h


DEFS_Debug := \
	'-D_DEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Debug :=

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-O0 \
	-Wall \
	-g \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Debug := \
	-I$(srcdir)/third_party/giflib-5.1.3 \
	-I$(srcdir)/third_party/giflib-5.1.3/lib

DEFS_Release := \
	'-DNDEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Release :=

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-O3 \
	-Wall \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Release := \
	-I$(srcdir)/third_party/giflib-5.1.3 \
	-I$(srcdir)/third_party/giflib-5.1.3/lib

OBJS := \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/dgif_lib.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/egif_lib.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/gif_err.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/gif_font.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/gif_hash.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/gifalloc.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/openbsd-reallocarray.o \
	$(obj).target/$(TARGET)/third_party/giflib-5.1.3/lib/quantize.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_picasso_gyp_gif_target_install_header1_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/libgif.so: | $(action_picasso_gyp_gif_target_install_header1_outputs)

# Preserve order dependency of special output on deps.
$(action_picasso_gyp_gif_target_install_header1_outputs): | 

LDFLAGS_Debug :=

LDFLAGS_Release :=

LIBS :=

$(obj).target/libgif.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libgif.so: LIBS := $(LIBS)
$(obj).target/libgif.so: LD_INPUTS := $(OBJS)
$(obj).target/libgif.so: TOOLSET := $(TOOLSET)
$(obj).target/libgif.so: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/libgif.so
# Add target alias
.PHONY: gif
gif: $(builddir)/lib.target/libgif.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libgif.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libgif.so: $(obj).target/libgif.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libgif.so
# Short alias for building this shared library.
.PHONY: libgif.so
libgif.so: $(obj).target/libgif.so $(builddir)/lib.target/libgif.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libgif.so

