# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := jpeg
### Rules for action "install_header1":
quiet_cmd_picasso_gyp_jpeg_target_install_header1 = ACTION picasso_gyp_jpeg_target_install_header1 $@
cmd_picasso_gyp_jpeg_target_install_header1 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/libjpeg-turbo-1.4.1/jpeglib.h "$(builddir)/include/jpeglib.h"

$(builddir)/include/jpeglib.h: obj := $(abs_obj)
$(builddir)/include/jpeglib.h: builddir := $(abs_builddir)
$(builddir)/include/jpeglib.h: TOOLSET := $(TOOLSET)
$(builddir)/include/jpeglib.h: $(srcdir)/third_party/libjpeg-turbo-1.4.1/jpeglib.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_jpeg_target_install_header1)

all_deps += $(builddir)/include/jpeglib.h
action_picasso_gyp_jpeg_target_install_header1_outputs := $(builddir)/include/jpeglib.h

### Rules for action "install_header2":
quiet_cmd_picasso_gyp_jpeg_target_install_header2 = ACTION picasso_gyp_jpeg_target_install_header2 $@
cmd_picasso_gyp_jpeg_target_install_header2 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/libjpeg-turbo-1.4.1/build/jconfig.h "$(builddir)/include/jconfig.h"

$(builddir)/include/jconfig.h: obj := $(abs_obj)
$(builddir)/include/jconfig.h: builddir := $(abs_builddir)
$(builddir)/include/jconfig.h: TOOLSET := $(TOOLSET)
$(builddir)/include/jconfig.h: $(srcdir)/third_party/libjpeg-turbo-1.4.1/build/jconfig.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_jpeg_target_install_header2)

all_deps += $(builddir)/include/jconfig.h
action_picasso_gyp_jpeg_target_install_header2_outputs := $(builddir)/include/jconfig.h

### Rules for action "install_header3":
quiet_cmd_picasso_gyp_jpeg_target_install_header3 = ACTION picasso_gyp_jpeg_target_install_header3 $@
cmd_picasso_gyp_jpeg_target_install_header3 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/libjpeg-turbo-1.4.1/jmorecfg.h "$(builddir)/include/jmorecfg.h"

$(builddir)/include/jmorecfg.h: obj := $(abs_obj)
$(builddir)/include/jmorecfg.h: builddir := $(abs_builddir)
$(builddir)/include/jmorecfg.h: TOOLSET := $(TOOLSET)
$(builddir)/include/jmorecfg.h: $(srcdir)/third_party/libjpeg-turbo-1.4.1/jmorecfg.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_jpeg_target_install_header3)

all_deps += $(builddir)/include/jmorecfg.h
action_picasso_gyp_jpeg_target_install_header3_outputs := $(builddir)/include/jmorecfg.h


DEFS_Debug := \
	'-D_DEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Debug :=

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-O0 \
	-Wall \
	-g \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Debug := \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1 \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1/build \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1/simd

DEFS_Release := \
	'-DNDEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Release :=

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-O3 \
	-Wall \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Release := \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1 \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1/build \
	-I$(srcdir)/third_party/libjpeg-turbo-1.4.1/simd

OBJS := \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcapimin.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcapistd.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jccoefct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jccolor.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcdctmgr.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jchuff.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcinit.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcmainct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcmarker.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcmaster.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcomapi.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcparam.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcphuff.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcprepct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcsample.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jctrans.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdapimin.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdapistd.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdatadst.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdatasrc.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdcoefct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdcolor.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jddctmgr.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdhuff.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdinput.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdmainct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdmarker.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdmaster.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdmerge.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdphuff.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdpostct.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdsample.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdtrans.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jerror.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jfdctflt.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jfdctfst.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jfdctint.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jidctflt.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jidctfst.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jidctint.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jidctred.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jquant1.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jquant2.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jutils.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jmemmgr.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jmemnobs.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jaricom.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jcarith.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdarith.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/turbojpeg.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/transupp.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdatadst-tj.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jdatasrc-tj.o \
	$(obj).target/$(TARGET)/third_party/libjpeg-turbo-1.4.1/jsimd_none.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_picasso_gyp_jpeg_target_install_header1_outputs) $(action_picasso_gyp_jpeg_target_install_header2_outputs) $(action_picasso_gyp_jpeg_target_install_header3_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/libjpeg.so: | $(action_picasso_gyp_jpeg_target_install_header1_outputs) $(action_picasso_gyp_jpeg_target_install_header2_outputs) $(action_picasso_gyp_jpeg_target_install_header3_outputs)

# Preserve order dependency of special output on deps.
$(action_picasso_gyp_jpeg_target_install_header1_outputs) $(action_picasso_gyp_jpeg_target_install_header2_outputs) $(action_picasso_gyp_jpeg_target_install_header3_outputs): | 

LDFLAGS_Debug :=

LDFLAGS_Release :=

LIBS :=

$(obj).target/libjpeg.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libjpeg.so: LIBS := $(LIBS)
$(obj).target/libjpeg.so: LD_INPUTS := $(OBJS)
$(obj).target/libjpeg.so: TOOLSET := $(TOOLSET)
$(obj).target/libjpeg.so: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/libjpeg.so
# Add target alias
.PHONY: jpeg
jpeg: $(builddir)/lib.target/libjpeg.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libjpeg.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libjpeg.so: $(obj).target/libjpeg.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libjpeg.so
# Short alias for building this shared library.
.PHONY: libjpeg.so
libjpeg.so: $(obj).target/libjpeg.so $(builddir)/lib.target/libjpeg.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libjpeg.so

