# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := picasso2_sw
DEFS_Debug := \
	'-DEXPORT' \
	'-D_DEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Debug :=

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-O0 \
	-Wall \
	-g \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Debug := \
	-I$(srcdir)/include \
	-I$(srcdir)/build \
	-I$(srcdir)/src \
	-I$(srcdir)/src/include \
	-I$(srcdir)/src/simd \
	-I$(srcdir)/src/gfx

DEFS_Release := \
	'-DEXPORT' \
	'-DNDEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Release :=

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-O3 \
	-Wall \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Release := \
	-I$(srcdir)/include \
	-I$(srcdir)/build \
	-I$(srcdir)/src \
	-I$(srcdir)/src/include \
	-I$(srcdir)/src/simd \
	-I$(srcdir)/src/gfx

OBJS := \
	$(obj).target/$(TARGET)/src/core/curve.o \
	$(obj).target/$(TARGET)/src/core/device.o \
	$(obj).target/$(TARGET)/src/core/graphic_path.o \
	$(obj).target/$(TARGET)/src/core/clipper.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_blur.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_device.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_font_adapter_freetype2.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_font_adapter_win32.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_font_load_freetype2.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_gradient_adapter.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_raster_adapter.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_rendering_buffer.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_sqrt_tables.o \
	$(obj).target/$(TARGET)/src/gfx/gfx_image_filters.o \
	$(obj).target/$(TARGET)/src/picasso_api.o \
	$(obj).target/$(TARGET)/src/picasso_canvas.o \
	$(obj).target/$(TARGET)/src/picasso_font_api.o \
	$(obj).target/$(TARGET)/src/picasso_font.o \
	$(obj).target/$(TARGET)/src/picasso_gradient_api.o \
	$(obj).target/$(TARGET)/src/picasso_gradient.o \
	$(obj).target/$(TARGET)/src/picasso_image.o \
	$(obj).target/$(TARGET)/src/picasso_mask_api.o \
	$(obj).target/$(TARGET)/src/picasso_mask.o \
	$(obj).target/$(TARGET)/src/picasso_matrix_api.o \
	$(obj).target/$(TARGET)/src/picasso_matrix.o \
	$(obj).target/$(TARGET)/src/picasso_painter.o \
	$(obj).target/$(TARGET)/src/picasso_path.o \
	$(obj).target/$(TARGET)/src/picasso_pattern.o \
	$(obj).target/$(TARGET)/src/picasso_raster_adapter.o \
	$(obj).target/$(TARGET)/src/picasso_rendering_buffer.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug :=

LDFLAGS_Release :=

LIBS := \
	-lfreetype \
	-lfontconfig

$(obj).target/libpicasso2_sw.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libpicasso2_sw.so: LIBS := $(LIBS)
$(obj).target/libpicasso2_sw.so: LD_INPUTS := $(OBJS)
$(obj).target/libpicasso2_sw.so: TOOLSET := $(TOOLSET)
$(obj).target/libpicasso2_sw.so: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/libpicasso2_sw.so
# Add target alias
.PHONY: picasso2_sw
picasso2_sw: $(builddir)/lib.target/libpicasso2_sw.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libpicasso2_sw.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libpicasso2_sw.so: $(obj).target/libpicasso2_sw.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libpicasso2_sw.so
# Short alias for building this shared library.
.PHONY: libpicasso2_sw.so
libpicasso2_sw.so: $(obj).target/libpicasso2_sw.so $(builddir)/lib.target/libpicasso2_sw.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libpicasso2_sw.so

