# This file is generated by gyp; do not edit.

export builddir_name ?= proj/./out
.PHONY: all
all:
	$(MAKE) zlib picasso2_sw bitblt text mask flowers gradient pattern composite part clock path psx_image alpha tiger clip gamma png image_info gif gcstate subwaymap blur threads shadow jpeg psxm_image_jpeg image_view psxm_image_png psxm_image_gif
