# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := zlib
### Rules for action "install_header1":
quiet_cmd_picasso_gyp_zlib_target_install_header1 = ACTION picasso_gyp_zlib_target_install_header1 $@
cmd_picasso_gyp_zlib_target_install_header1 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/zlib-1.2.8/zconf.h "$(builddir)/include/zconf.h"

$(builddir)/include/zconf.h: obj := $(abs_obj)
$(builddir)/include/zconf.h: builddir := $(abs_builddir)
$(builddir)/include/zconf.h: TOOLSET := $(TOOLSET)
$(builddir)/include/zconf.h: $(srcdir)/third_party/zlib-1.2.8/zconf.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_zlib_target_install_header1)

all_deps += $(builddir)/include/zconf.h
action_picasso_gyp_zlib_target_install_header1_outputs := $(builddir)/include/zconf.h

### Rules for action "install_header2":
quiet_cmd_picasso_gyp_zlib_target_install_header2 = ACTION picasso_gyp_zlib_target_install_header2 $@
cmd_picasso_gyp_zlib_target_install_header2 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p $(builddir)/include; python tools/cp.py third_party/zlib-1.2.8/zlib.h "$(builddir)/include/zlib.h"

$(builddir)/include/zlib.h: obj := $(abs_obj)
$(builddir)/include/zlib.h: builddir := $(abs_builddir)
$(builddir)/include/zlib.h: TOOLSET := $(TOOLSET)
$(builddir)/include/zlib.h: $(srcdir)/third_party/zlib-1.2.8/zlib.h FORCE_DO_CMD
	$(call do_cmd,picasso_gyp_zlib_target_install_header2)

all_deps += $(builddir)/include/zlib.h
action_picasso_gyp_zlib_target_install_header2_outputs := $(builddir)/include/zlib.h


DEFS_Debug := \
	'-DZLIB_DLL' \
	'-D_DEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Debug :=

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-O0 \
	-Wall \
	-g \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Debug := \
	-I$(srcdir)/third_party/zlib-1.2.8 \
	-I$(builddir)/include

DEFS_Release := \
	'-DZLIB_DLL' \
	'-DNDEBUG' \
	'-DENABLE_FREE_TYPE2=1' \
	'-DENABLE_FONT_CONFIG=1'

# Flags passed to all source files.
CFLAGS_Release :=

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-O3 \
	-Wall \
	-fPIC \
	-fno-rtti \
	-fno-exceptions \
	-Wno-unused-result

INCS_Release := \
	-I$(srcdir)/third_party/zlib-1.2.8 \
	-I$(builddir)/include

OBJS := \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/adler32.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/compress.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/crc32.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/deflate.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/infback.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/inffast.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/inflate.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/inftrees.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/trees.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/uncompr.o \
	$(obj).target/$(TARGET)/third_party/zlib-1.2.8/zutil.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_picasso_gyp_zlib_target_install_header1_outputs) $(action_picasso_gyp_zlib_target_install_header2_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/libzlib.so: | $(action_picasso_gyp_zlib_target_install_header1_outputs) $(action_picasso_gyp_zlib_target_install_header2_outputs)

# Preserve order dependency of special output on deps.
$(action_picasso_gyp_zlib_target_install_header1_outputs) $(action_picasso_gyp_zlib_target_install_header2_outputs): | 

LDFLAGS_Debug :=

LDFLAGS_Release :=

LIBS :=

$(obj).target/libzlib.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libzlib.so: LIBS := $(LIBS)
$(obj).target/libzlib.so: LD_INPUTS := $(OBJS)
$(obj).target/libzlib.so: TOOLSET := $(TOOLSET)
$(obj).target/libzlib.so: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/libzlib.so
# Add target alias
.PHONY: zlib
zlib: $(builddir)/lib.target/libzlib.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libzlib.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libzlib.so: $(obj).target/libzlib.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libzlib.so
# Short alias for building this shared library.
.PHONY: libzlib.so
libzlib.so: $(obj).target/libzlib.so $(builddir)/lib.target/libzlib.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libzlib.so

